# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "JustApp" do

pod "MMDrawerController"
pod "DDExpandableButton"
pod "SVProgressHUD"
pod "PSLocationManager"

end

target "JustAppTests" do

end

